import { cn } from "@/lib/utils";
import Providers from "@/providers";
import type { Metadata } from "next";
import { Lato, Roboto } from "next/font/google";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontHeading = Roboto({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const fontBody = Lato({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(fontHeading.variable, fontBody.variable, "h-full")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
